# Интервал выдачи предметов в секундах
interval-seconds: 1  # теперь каждую секунду

# Список предметов для выдачи в формате: МАТЕРИАЛ:КОЛИЧЕСТВО
items:
  - "DIAMOND:1"
  - "APPLE:5"
  - "COOKED_BEEF:3"

give-message: "§aВы получили предметы!"