name: Randomitems
version: 1.0
main: org.plaginsp.untitled.Randomitems
api-version: 1.17

commands:
  randomitemsreload:
    description: Перезагружает конфигурацию плагина
    usage: /randomitemsreload
    aliases: [rireload, rir]

permissions:
  randomitems.reload:
    description: Позволяет перезагружать конфигурацию плагина
    default: op